<#
.SYNOPSIS
    Zasób tłumaczeń AccessGuy (PowerShell) — launcher + skaner.
.DESCRIPTION
    Jedno źródło napisów dla wszystkich skryptów PS. Język wybierany przez $script:AgLang
    (ustawiany z parametru -Lang albo z menu [L]). Domyślnie 'en'. Dodanie kolejnego języka
    (np. 'de') = dopisanie podtablicy o IDENTYCZNYCH kluczach.

    Skaner i procesor NIE współdzielą biblioteki (złota zasada CLAUDE.md) — to jest osobny,
    powerShellowy katalog, lustrzany wobec processor/i18n po stronie sensu, nie kodu.

    Użycie:  (T 'menu.title')              # prosty napis
             (T 'panel.consents') -f $n    # z placeholderem {0} (składnia -f PowerShella)
#>

if (-not (Get-Variable -Name AgLang -Scope Script -ErrorAction SilentlyContinue)) {
    $script:AgLang = 'en'
}

# Języki dostępne w menu [L]. Kolejność = kolejność prezentacji.
$script:AgLanguages = [ordered]@{
    en = 'English'
    pl = 'Polski'
}

$script:AgStrings = @{
    en = @{
        # --- panel / branding ---
        'panel.subtitle'      = 'Read-only Microsoft Entra ID access review'
        'panel.author'        = 'Author: '
        'panel.authz_title'   = 'PACKAGE COMPONENT AUTHORIZATION STATUS'
        'panel.unblocked'     = '— unblocked / allowed'
        'panel.consents'      = 'Consent obtained for {0} components — no more manual confirmations.'
        'panel.none_unblock'  = '(no additional scripts to unblock found)'
        # --- menu ---
        'menu.choose'         = 'Choose a mode:'
        'menu.scan'           = 'AccessGuy-EntraID-Scanner   '
        'menu.scan_desc'      = '— tenant scan (PowerShell, read-only)'
        'menu.report'         = 'AccessGuy-Report-Builder    '
        'menu.report_desc'    = '— report for management (python3 required)'
        'menu.language'       = 'Language / Język'
        'menu.quit'           = 'Quit'
        'menu.lang_current'   = '(current: {0})'
        'menu.lang_prompt'    = 'Pick a language'
        'menu.unknown'        = 'Unknown option. Type 1, 2, D, L or Q.'
        'menu.bye'            = 'See you!'
        'menu.return'         = 'Return to menu? [y/N]'
        'menu.return_yes'     = 'y'
        'menu.deps'           = 'Dependencies                '
        'menu.deps_desc'      = '— check before scan'
        'panel.deps_hint'     = 'Tip: press [D] to check dependencies before scanning.'
        # --- [D] dependencies / pre-scan check ---
        'deps.title'          = 'DEPENDENCIES / PRE-SCAN CHECK'
        'deps.sec.components' = 'Package components (authorized)'
        'deps.sec.graph'      = 'Microsoft Graph permissions used'
        'deps.sec.runtime'    = 'Runtime / external tools'
        'deps.sec.output'     = 'Output folders access (read/write)'
        'deps.required'       = '(required)'
        'deps.notfound'       = 'not found'
        'deps.writable'       = 'read/write OK'
        'deps.not_writable'   = 'NO write access'
        'deps.python_purpose' = 'needed for the report builder (mode [2])'
        'deps.sevenzip_purpose' = 'needed only to encrypt the output (optional)'
        'deps.out_dir'        = 'out/ (scan datasets)'
        'deps.reports_dir'    = 'reports/ (generated reports)'
        'deps.back'           = 'Press Enter to return to the menu'
        'deps.scope.user'        = 'Accounts, sign-in activity, managers'
        'deps.scope.directory'   = 'Tenant, verified domains, org-wide read'
        'deps.scope.audit'       = 'PIM history + app credential events'
        'deps.scope.role'        = 'Role assignments (active / eligible / PIM)'
        'deps.scope.app'         = 'App registrations, service principals, OAuth grants'
        'deps.scope.authmethod'  = 'MFA registration state'
        'deps.scope.policy'      = 'Conditional Access + tenant policies'
        'deps.scope.risky'       = 'Identity Protection risky users'
        # --- scan mode ---
        'scan.not_found'      = '  [-] Scanner not found: {0}'
        'scan.header'         = '  >> AccessGuy-EntraID-Scanner — SCAN phase (read-only)'
        'scan.login_hint'     = '     Sign in as an operator with the Global Reader role (MFA OK).'
        'scan.scope_title'    = '  Scan scope (what to collect):'
        'scan.scope_all'      = 'Everything'
        'scan.scope_all_d'    = '       — accounts + groups + applications (recommended)'
        'scan.scope_users'    = 'Accounts'
        'scan.scope_users_d'  = '          — users, roles, MFA, sign-ins'
        'scan.scope_groups'   = 'Groups'
        'scan.scope_groups_d' = '          — group inventory, owners, group roles/licenses'
        'scan.scope_apps'     = 'Applications'
        'scan.scope_apps_d'   = '   — registrations, credentials, app/delegated permissions'
        'scan.scope_prompt'   = '  > [Enter = 1]'
        'scan.login_title'    = '  Sign-in method:'
        'scan.login_browser'  = 'Browser'
        'scan.login_browser_d'= '  — opens a sign-in window (requires a GUI)'
        'scan.login_device'   = 'Device code'
        'scan.login_device_d' = ' — you get a URL + code, confirm in Authenticator (recommended on Linux)'
        'scan.login_prompt'   = '  >'
        # --- report mode (builder) ---
        'report.header'       = '  >> AccessGuy-Report-Builder — REPORT phase  (report ideal for management review)'
        'report.requires'     = '     Requires: Python 3.11+'
        'report.no_python'    = '  [-] Python 3.11+ not detected. Install Python 3 and run mode [2] again.'
        'report.install_hint' = '      Windows: winget install Python.Python.3.12   ·   Linux: sudo apt install python3 python3-venv'
        'report.detected'     = '  [+] Detected: {0}  ({1})'
        'report.no_proc'      = '  [-] Processor directory not found: {0}'
        'report.venv_create'  = '  [*] Creating the builder environment (venv) (one-time)...'
        'report.venv_fail'    = '  [-] Failed to create venv. On Kali/Debian also install:'
        'report.venv_fail_cmd'= '      sudo apt install -y python3-venv'
        'report.deps'         = '  [*] Installing builder dependencies (one-time)...'
        'report.pdf_fail'     = '  [!] The [pdf] variant failed (missing system libraries for PDF). Installing without PDF (HTML is nicer anyway)...'
        'report.install_fail' = '  [-] Builder installation failed (accessguy_processor module unavailable).'
        'report.try_manual'   = '      Try manually:  cd processor && python3 -m venv .venv && .venv/bin/pip install -e .'
        'report.ready'        = '  [+] Builder ready.'
        # --- lite report (ReportLite) ---
        'lite.sig.priv_no_mfa'= 'PRIV without MFA'
        'lite.sig.inactive'   = 'inactive {0} d'
        'lite.sig.never'      = 'never signed in'
        'lite.title'          = 'AccessGuy — LITE report'
        'lite.h1'             = 'AccessGuy — LITE report (no-Python fallback)'
        'lite.meta'           = 'Tenant: {0} · Generated: {1} · Mode: {2} · Accounts: {3}'
        'lite.col_name'       = 'Name'
        'lite.col_upn'        = 'UPN'
        'lite.col_category'   = 'Category'
        'lite.col_status'     = 'Status'
        'lite.col_since'      = 'Since sign-in'
        'lite.col_priv'       = 'Priv'
        'lite.col_signals'    = 'Signals'
        'lite.yes'            = 'YES'
        'lite.note'           = 'This is a simplified preview. Full scoring (rules.yaml), severity and recommendations + a nicer HTML/PDF are generated by the Python processor from dataset.json.<br>Author: Daniel "NewLife" Budyn.'
        # --- banner (Common.ps1) ---
        'banner.connecting'   = '  Connecting to Microsoft Entra ID (read-only)...'
        'banner.perms_title'  = 'REQUIRED PERMISSIONS (Microsoft Graph):'
        'banner.recommended'  = '(recommended)'
        'banner.prereq_title' = 'PREREQUISITES:'
        'banner.prereq_role'  = '  - Operator role: Global Reader (or Security Reader + Reports Reader)'
        'banner.prereq_lic'   = '  - Tenant license: Entra ID P1/P2 (for signInActivity), P2 for full PIM'
        # --- scan runtime (Invoke-AccessGuyScan.ps1) ---
        'scan.connect_fail'   = 'Connection to Microsoft Graph failed.'
        'scan.connected'      = 'Connected. Tenant: {0}  ·  AuthType: {1}'
        'scan.collecting'     = 'Signed in. Starting data collection (read-only)...'
        'scan.scope_is'       = 'Scan scope: {0}'
        'scan.got.users'      = '  \-> accounts captured: {0}'
        'scan.got.mfa'        = '  \-> MFA registrations: {0}'
        'scan.got.audit'      = '  \-> audit entries (PIM + app mgmt): {0}'
        'scan.got.signins'    = '  \-> sign-ins ({0} d): {1}'
        'scan.got.risky'      = '  \-> accounts with unremediated risk (Identity Protection): {0}'
        'scan.got.roles'      = '  \-> role assignments captured: {0}'
        'scan.got.groups'     = '  \-> groups captured: {0}'
        'scan.got.apps'       = '  \-> apps/SP captured: {0}, registrations: {1}, OAuth grants: {2}'
        'scan.got.spsignins'  = '  \-> SP sign-in activities: {0}'
        'scan.got.capolicies' = '  \-> Conditional Access policies: {0}'
        'scan.got.posture'    = '  \-> tenant posture (authorization/security defaults/auth methods) read'
        'scan.dataset_saved'  = 'Dataset saved: {0}'
        'scan.lite_saved'     = 'Lite report: {0}'
        'scan.done'           = 'Scan complete. Next step: report builder (mode [2] in NewLife-AccessGuy).'
        'scan.aborted'        = 'Scan aborted: {0}'
        'scan.keyring_hint'   = 'This is a Linux keyring issue. Run with device-code login: ./Invoke-AccessGuyScan.ps1 -DeviceCode  (token is not written to disk — ContextScope Process).'
        # --- auth (Auth.ps1) ---
        'auth.delegated'      = 'Auth: delegated (interactive). Sign in as an operator with the Global Reader role.'
        'auth.devicecode'     = 'Device-code login: a URL and CODE will appear shortly (confirm in Authenticator). Wait a few seconds...'
        'auth.mi'             = 'Auth: app-only (Managed Identity).'
        'auth.cert'           = 'Auth: app-only (certificate).'
        'auth.cert_needs'     = 'App + certificate requires -TenantId and -ClientId.'
        'auth.app_needs'      = 'App mode requires -UseManagedIdentity or -CertThumbprint (+ -TenantId -ClientId). Client secret intentionally omitted from the skeleton — if you must, pull it from Key Vault and use -ClientSecretCredential.'
        'auth.missing_scopes' = "Missing scopes (sections will be skipped): {0}"
        'auth.p2_unconfirmed' = 'Could not confirm P1/P2 — inactivity scoring will be best-effort.'
        'auth.no_p2'          = 'No P1/P2: signInActivity will be empty.'
        'auth.domains_fail'   = 'Could not fetch verifiedDomains: {0}'
        # --- collectors (Collectors.ps1) ---
        'col.running'         = 'Collector: {0} ...'
        'col.failed'          = "Collector '{0}' failed: {1}"
        'conn.engage'         = 'tapping graph connector ...'
        'conn.map_title'      = 'GRAPH CONNECTOR MAP'
        'conn.why.users'       = 'Every identity is a way in - who exists, who is stale, who can still sign in.'
        'conn.why.authMethods' = 'Who can actually resist phishing - a privileged account without MFA is the fastest way in.'
        'conn.why.audit'       = 'The paper trail - who activated a role or added a secret, and when.'
        'conn.why.signIns'     = 'Behaviour: night logons, legacy auth, risky IPs - normal users vs probable incidents.'
        'conn.why.riskyUsers'  = 'Accounts Microsoft already flags as risky - unremediated risk is an unanswered alarm.'
        'conn.why.roles'       = 'The keys to the kingdom - who holds privilege, directly or via PIM.'
        'conn.why.groups'      = 'Access in bulk - one role-assignable group can silently turn members into admins.'
        'conn.why.apps'        = 'Service principals and OAuth grants act unattended - a high-priv app secret rivals an admin password.'
        'conn.why.spSignIns'   = 'When workload identities last signed in - dormant high-priv apps are quiet backdoors.'
        'conn.why.caPolicies'  = 'The gate that enforces MFA and blocks legacy auth - gaps and exclusions are where attackers walk in.'
        # --- graph paging (Common.ps1) ---
        'graph.retry'         = 'Graph {0} — retrying {1}/{2} in {3}s ...'
        # --- connector intel: what each data source tells us (hacker briefing) ---
        'intel.title'         = 'INTEL // WHAT THE CONNECTORS REVEAL'
        'intel.users'         = 'Accounts are the attack surface — every identity is a way in. We map who exists, who is stale, and who can still sign in.'
        'intel.groups'        = 'Groups grant access in bulk; one role-assignable group can silently turn members into admins. We chart membership, owners and group-borne roles.'
        'intel.roles'         = 'Role assignments are the keys to the kingdom — who holds privilege, directly or via PIM. Too many standing admins widen the blast radius.'
        'intel.apps'          = 'Service principals and OAuth grants act for users and apps, often unattended. A high-privilege app secret is as dangerous as an admin password.'
        'intel.applications'  = 'App registrations carry credentials (secrets/certs) and API permissions. A live-but-expired secret or app-only privilege is a classic backdoor.'
        'intel.mfa'           = 'MFA registration shows who can actually resist phishing. A privileged account without MFA is the fastest path to full compromise.'
        'intel.audit'         = 'Audit (PIM + app management) is the paper trail — who activated a role, who added a secret, and when. It turns hypotheses into evidence.'
        'intel.signins'       = 'Sign-in logs expose behaviour: night logons, legacy auth, risky IPs. The patterns here separate normal users from probable incidents.'
        'intel.skus'          = 'Licenses (SKUs) reveal which security features the tenant even owns. No P1/P2 means blind spots in sign-in and risk telemetry.'
        'intel.capolicies'    = 'Conditional Access is the gate that enforces MFA and blocks legacy auth. Gaps and exclusions here are where attackers walk straight in.'
        'intel.riskyusers'    = 'Identity Protection flags accounts Microsoft already considers risky. Unremediated risk is a fire alarm nobody answered.'
        # --- protect / encrypted archive (Protect.ps1) ---
        'protect.packing'     = 'Securing output into an encrypted archive (AES-256)...'
        'protect.no7z'        = 'No 7-Zip found (7z/7za/7zz). Skipping encryption — files left in plaintext. Install 7-Zip for protected output.'
        'protect.nothing'     = 'Nothing to secure (no output files found).'
        'protect.done'        = 'Encrypted archive: {0}'
        'protect.removed'     = 'Plaintext files removed — only the encrypted archive remains.'
        'protect.fail'        = 'Encryption failed ({0}). Plaintext files left intact.'
        'protect.pw_title'    = 'ARCHIVE PASSWORD — SHOWN ONCE, SAVE IT NOW'
        'protect.pw_warn'     = 'This password is NOT stored anywhere. Lose it and the archive is unrecoverable.'
        'protect.ask'         = 'Encrypt the output into a password-protected archive (7-Zip / AES-256)? [y/N]'
        'protect.yes'         = 'y'
        'protect.skipped'     = 'Skipped — files left in plaintext.'
        'protect.r1_note'     = 'Heads-up: the report builder (mode [2]) can ALSO encrypt the final output. If you encrypt the dataset NOW, the Python builder will NOT be able to read it until you extract it.'
        'protect.r1_skipped'  = 'Dataset left in plaintext — it will be protected after you build the report (mode [2]).'
        'protect.r2_note'     = 'Note: an encrypted archive CANNOT be re-processed by the builder — extract it first if you want to rebuild.'
        # --- scan summary box (Common.ps1 / Show-AgScanSummary) ---
        'sum.title'           = 'SCAN COMPLETE -- HERE IS WHAT WE CAPTURED'
        'sum.warnings'        = 'Warnings'
        'sum.quote'           = '   "I will not sell your data. Do you trust me?"  '
        'sum.row.users'       = 'Accounts (users)'
        'sum.row.groups'      = 'Groups'
        'sum.row.roles'       = 'Role assignments'
        'sum.row.apps'        = 'Applications / SP'
        'sum.row.applications'= 'App registrations'
        'sum.row.grants'      = 'OAuth grants'
        'sum.row.mfa'         = 'MFA registrations'
        'sum.row.audit'       = 'Audit entries (PIM)'
        'sum.row.signins'     = 'Sign-ins (30 d)'
        'sum.row.skus'        = 'Licenses (SKU)'
        'sum.row.capolicies'  = 'CA policies'
        'sum.row.riskyusers'  = 'atRisk accounts (IdP)'
    }
    pl = @{
        'panel.subtitle'      = 'Read-only przegląd uprawnień Microsoft Entra ID'
        'panel.author'        = 'Autor: '
        'panel.authz_title'   = 'STATUS AUTORYZACJI ELEMENTÓW PAKIETU'
        'panel.unblocked'     = '— odblokowany / dopuszczony'
        'panel.consents'      = 'Zgody uzyskane dla {0} elementów — nie musisz już potwierdzać ręcznie.'
        'panel.none_unblock'  = '(nie znaleziono dodatkowych skryptów do odblokowania)'
        'menu.choose'         = 'Wybierz tryb:'
        'menu.scan'           = 'AccessGuy-EntraID-Scanner   '
        'menu.scan_desc'      = '— skan tenanta (PowerShell, read-only)'
        'menu.report'         = 'AccessGuy-Report-Builder    '
        'menu.report_desc'    = '— raport dla zarządu (python3 required)'
        'menu.language'       = 'Language / Język'
        'menu.quit'           = 'Wyjście'
        'menu.lang_current'   = '(aktualny: {0})'
        'menu.lang_prompt'    = 'Wybierz język'
        'menu.unknown'        = 'Nieznana opcja. Wpisz 1, 2, D, L albo Q.'
        'menu.bye'            = 'Do zobaczenia!'
        'menu.return'         = 'Wrócić do menu? [t/N]'
        'menu.return_yes'     = 't'
        'menu.deps'           = 'Komponenty                  '
        'menu.deps_desc'      = '— sprawdź przed skanem'
        'panel.deps_hint'     = 'Wskazówka: wciśnij [D], aby sprawdzić komponenty przed skanem.'
        # --- [D] komponenty / sprawdzenie przed skanem ---
        'deps.title'          = 'KOMPONENTY / SPRAWDZENIE PRZED SKANEM'
        'deps.sec.components' = 'Komponenty pakietu (autoryzowane)'
        'deps.sec.graph'      = 'Wykorzystywane uprawnienia Microsoft Graph'
        'deps.sec.runtime'    = 'Środowisko / narzędzia zewnętrzne'
        'deps.sec.output'     = 'Dostęp do folderów wyjściowych (odczyt/zapis)'
        'deps.required'       = '(wymagane)'
        'deps.notfound'       = 'nie znaleziono'
        'deps.writable'       = 'odczyt/zapis OK'
        'deps.not_writable'   = 'BRAK zapisu'
        'deps.python_purpose' = 'potrzebny do buildera raportu (tryb [2])'
        'deps.sevenzip_purpose' = 'potrzebny tylko do szyfrowania wyniku (opcjonalnie)'
        'deps.out_dir'        = 'out/ (datasety skanu)'
        'deps.reports_dir'    = 'reports/ (wygenerowane raporty)'
        'deps.back'           = 'Naciśnij Enter, aby wrócić do menu'
        'deps.scope.user'        = 'Konta, aktywność logowań, menedżerowie'
        'deps.scope.directory'   = 'Tenant, zweryfikowane domeny, odczyt całej organizacji'
        'deps.scope.audit'       = 'Historia PIM + zdarzenia poświadczeń aplikacji'
        'deps.scope.role'        = 'Przypisania ról (aktywne / kwalifikowalne / PIM)'
        'deps.scope.app'         = 'Rejestracje aplikacji, SP, zgody OAuth'
        'deps.scope.authmethod'  = 'Stan rejestracji MFA'
        'deps.scope.policy'      = 'Conditional Access + polityki tenanta'
        'deps.scope.risky'       = 'Ryzykowni użytkownicy (Identity Protection)'
        'scan.not_found'      = '  [-] Nie znaleziono skanera: {0}'
        'scan.header'         = '  >> AccessGuy-EntraID-Scanner — faza SKAN (read-only)'
        'scan.login_hint'     = '     Zaloguj się jako operator z rolą Global Reader (MFA OK).'
        'scan.scope_title'    = '  Zakres skanu (co zebrać):'
        'scan.scope_all'      = 'Wszystko'
        'scan.scope_all_d'    = '       — konta + grupy + aplikacje (zalecane)'
        'scan.scope_users'    = 'Konta'
        'scan.scope_users_d'  = '          — użytkownicy, role, MFA, logowania'
        'scan.scope_groups'   = 'Grupy'
        'scan.scope_groups_d' = '          — inwentarz grup, właściciele, role/licencje grupowe'
        'scan.scope_apps'     = 'Aplikacje'
        'scan.scope_apps_d'   = '      — rejestracje, poświadczenia, uprawnienia app/delegated'
        'scan.scope_prompt'   = '  > [Enter = 1]'
        'scan.login_title'    = '  Metoda logowania:'
        'scan.login_browser'  = 'Przeglądarka'
        'scan.login_browser_d'= '  — otworzy okno logowania (wymaga GUI)'
        'scan.login_device'   = 'Kod (device code)'
        'scan.login_device_d' = ' — dostaniesz URL + kod, potwierdzasz w Authenticatorze (zalecane na Linux)'
        'scan.login_prompt'   = '  >'
        'report.header'       = '  >> AccessGuy-Report-Builder — faza RAPORT  (raport idealny do przeglądu dla zarządu)'
        'report.requires'     = '     Wymaga: Python 3.11+'
        'report.no_python'    = '  [-] Nie wykryto Pythona 3.11+ . Zainstaluj Python 3 i uruchom tryb [2] ponownie.'
        'report.install_hint' = '      Windows: winget install Python.Python.3.12   ·   Linux: sudo apt install python3 python3-venv'
        'report.detected'     = '  [+] Wykryto: {0}  ({1})'
        'report.no_proc'      = '  [-] Nie znaleziono katalogu procesora: {0}'
        'report.venv_create'  = '  [*] Tworzę środowisko (venv) buildera (jednorazowo)...'
        'report.venv_fail'    = '  [-] Nie udało się utworzyć venv. Na Kali/Debian doinstaluj:'
        'report.venv_fail_cmd'= '      sudo apt install -y python3-venv'
        'report.deps'         = '  [*] Instaluję zależności buildera (jednorazowo)...'
        'report.pdf_fail'     = '  [!] Wariant [pdf] nieudany (brak bibliotek systemowych dla PDF). Instaluję bez PDF (HTML i tak ładniejszy)...'
        'report.install_fail' = '  [-] Instalacja buildera nie powiodła się (moduł accessguy_processor niedostępny).'
        'report.try_manual'   = '      Spróbuj ręcznie:  cd processor && python3 -m venv .venv && .venv/bin/pip install -e .'
        'report.ready'        = '  [+] Builder gotowy.'
        'lite.sig.priv_no_mfa'= 'PRIV bez MFA'
        'lite.sig.inactive'   = 'nieaktywne {0} d'
        'lite.sig.never'      = 'nigdy nie logowane'
        'lite.title'          = 'AccessGuy — raport LITE'
        'lite.h1'             = 'AccessGuy — raport LITE (fallback bez Pythona)'
        'lite.meta'           = 'Tenant: {0} · Wygenerowano: {1} · Tryb: {2} · Kont: {3}'
        'lite.col_name'       = 'Nazwa'
        'lite.col_upn'        = 'UPN'
        'lite.col_category'   = 'Kategoria'
        'lite.col_status'     = 'Status'
        'lite.col_since'      = 'Od logowania'
        'lite.col_priv'       = 'Priv'
        'lite.col_signals'    = 'Sygnały'
        'lite.yes'            = 'TAK'
        'lite.note'           = 'To uproszczony podgląd. Pełny scoring (rules.yaml), severity i rekomendacje + ładny HTML/PDF generuje procesor Python z dataset.json.<br>Autor: Daniel "NewLife" Budyn.'
        # --- banner (Common.ps1) ---
        'banner.connecting'   = '  Łączenie z Microsoft Entra ID (read-only)...'
        'banner.perms_title'  = 'WYMAGANE UPRAWNIENIA (Microsoft Graph):'
        'banner.recommended'  = '(zalecane)'
        'banner.prereq_title' = 'PREREKWIZYTY:'
        'banner.prereq_role'  = '  - Rola operatora: Global Reader (lub Security Reader + Reports Reader)'
        'banner.prereq_lic'   = '  - Licencja tenanta: Entra ID P1/P2 (dla signInActivity), P2 dla pełnego PIM'
        # --- scan runtime (Invoke-AccessGuyScan.ps1) ---
        'scan.connect_fail'   = 'Połączenie z Microsoft Graph nie powiodło się.'
        'scan.connected'      = 'Połączono. Tenant: {0}  ·  AuthType: {1}'
        'scan.collecting'     = 'Zalogowano. Zaczynam zbieranie danych (read-only)...'
        'scan.scope_is'       = 'Zakres skanu: {0}'
        'scan.got.users'      = '  \-> złapano kont: {0}'
        'scan.got.mfa'        = '  \-> rejestracji MFA: {0}'
        'scan.got.audit'      = '  \-> wpisów audytu (PIM + app mgmt): {0}'
        'scan.got.signins'    = '  \-> logowań ({0} dni): {1}'
        'scan.got.risky'      = '  \-> kont z nieobsłużonym ryzykiem (Identity Protection): {0}'
        'scan.got.roles'      = '  \-> złapano przypisań ról: {0}'
        'scan.got.groups'     = '  \-> złapano grup: {0}'
        'scan.got.apps'       = '  \-> złapano aplikacji/SP: {0}, rejestracji: {1}, zgód OAuth: {2}'
        'scan.got.spsignins'  = '  \-> aktywności logowań SP: {0}'
        'scan.got.capolicies' = '  \-> polityk Conditional Access: {0}'
        'scan.got.posture'    = '  \-> postawa tenanta (authorization/security defaults/metody auth) odczytana'
        'scan.dataset_saved'  = 'Dataset zapisany: {0}'
        'scan.lite_saved'     = 'Lekki raport: {0}'
        'scan.done'           = 'Skan zakończony. Następny krok: builder raportu (tryb [2] w NewLife-AccessGuy).'
        'scan.aborted'        = 'Skan przerwany: {0}'
        'scan.keyring_hint'   = 'To problem keyringa Linuksa. Uruchom z logowaniem kodem: ./Invoke-AccessGuyScan.ps1 -DeviceCode  (token nie jest zapisywany na dysk — ContextScope Process).'
        # --- auth (Auth.ps1) ---
        'auth.delegated'      = 'Auth: delegated (interactive). Zaloguj się jako operator z rolą Global Reader.'
        'auth.devicecode'     = 'Logowanie kodem: za chwilę pojawi się URL i KOD (potwierdzasz w Authenticatorze). Czekaj kilka sekund...'
        'auth.mi'             = 'Auth: app-only (Managed Identity).'
        'auth.cert'           = 'Auth: app-only (certyfikat).'
        'auth.cert_needs'     = 'App + certyfikat wymaga -TenantId i -ClientId.'
        'auth.app_needs'      = 'Tryb App wymaga -UseManagedIdentity albo -CertThumbprint (+ -TenantId -ClientId). Client secret świadomie pominięty w szkielecie — jeśli musisz, pobierz go z Key Vault i użyj -ClientSecretCredential.'
        'auth.missing_scopes' = "Brakujące scope'y (sekcje zostaną pominięte): {0}"
        'auth.p2_unconfirmed' = 'Nie udało się potwierdzić P1/P2 — scoring nieaktywności będzie best-effort.'
        'auth.no_p2'          = 'Brak P1/P2: signInActivity będzie puste.'
        'auth.domains_fail'   = 'Nie udało się pobrać verifiedDomains: {0}'
        # --- collectors (Collectors.ps1) ---
        'col.running'         = 'Kolektor: {0} ...'
        'col.failed'          = "Kolektor '{0}' nieudany: {1}"
        'conn.engage'         = 'podpinam konektor graph ...'
        'conn.map_title'      = 'MAPA KONEKTOROW GRAPH'
        'conn.why.users'       = 'Kazda tozsamosc to drzwi do srodka - kto istnieje, kto martwy, kto wciaz sie loguje.'
        'conn.why.authMethods' = 'Kto realnie oprze sie phishingowi - konto uprzywilejowane bez MFA to najszybsza droga do srodka.'
        'conn.why.audit'       = 'Slad na papierze - kto aktywowal role albo dodal sekret i kiedy.'
        'conn.why.signIns'     = 'Zachowanie: nocne logowania, legacy auth, ryzykowne IP - normalni vs prawdopodobne incydenty.'
        'conn.why.riskyUsers'  = 'Konta, ktore Microsoft juz uznal za ryzykowne - nieobsluzone ryzyko to alarm bez odpowiedzi.'
        'conn.why.roles'       = 'Klucze do krolestwa - kto ma uprawnienia, wprost albo przez PIM.'
        'conn.why.groups'      = 'Dostep hurtem - jedna grupa role-assignable po cichu robi z czlonkow adminow.'
        'conn.why.apps'        = 'Service principal i zgody OAuth dzialaja bez nadzoru - sekret uprzywilejowanej apki to jak haslo admina.'
        'conn.why.spSignIns'   = 'Kiedy tozsamosci aplikacji logowaly sie ostatnio - uspione uprzywilejowane apki to ciche backdoory.'
        'conn.why.caPolicies'  = 'Brama wymuszajaca MFA i blokujaca legacy - luki i wykluczenia to wejscie dla atakujacego.'
        # --- graph paging (Common.ps1) ---
        'graph.retry'         = 'Graph {0} — ponawiam {1}/{2} za {3}s ...'
        # --- konektory: co mówi każde źródło danych (hakerski briefing) ---
        'intel.title'         = 'INTEL // CO ZDRADZAJĄ KONEKTORY'
        'intel.users'         = 'Konta to powierzchnia ataku — każda tożsamość to wejście. Mapujemy kto istnieje, kto jest martwy i kto wciąż może się zalogować.'
        'intel.groups'        = 'Grupy nadają dostęp hurtem; jedna grupa role-assignable po cichu robi z członków adminów. Spisujemy członkostwo, właścicieli i role nadane grupie.'
        'intel.roles'         = 'Przypisania ról to klucze do królestwa — kto ma uprzywilejowanie, wprost lub przez PIM. Za dużo stałych adminów to większy promień rażenia.'
        'intel.apps'          = 'Service principale i zgody OAuth działają za użytkowników i aplikacje, często bez nadzoru. Sekret uprzywilejowanej aplikacji jest groźny jak hasło admina.'
        'intel.applications'  = 'Rejestracje aplikacji niosą poświadczenia (sekrety/certy) i uprawnienia API. Żywy, ale wygasły sekret albo app-only privilege to klasyczny backdoor.'
        'intel.mfa'           = 'Rejestracja MFA pokazuje, kto realnie oprze się phishingowi. Uprzywilejowane konto bez MFA to najszybsza droga do pełnego przejęcia.'
        'intel.audit'         = 'Audyt (PIM + zarządzanie aplikacjami) to ślad — kto aktywował rolę, kto dodał sekret i kiedy. Zamienia hipotezy w dowody.'
        'intel.signins'       = 'Logi logowań zdradzają zachowanie: nocne logowania, legacy auth, ryzykowne IP. Wzorce tutaj oddzielają normalnych userów od prawdopodobnych incydentów.'
        'intel.skus'          = 'Licencje (SKU) mówią, jakie funkcje bezpieczeństwa tenant w ogóle posiada. Brak P1/P2 to ślepe pola w telemetrii logowań i ryzyka.'
        'intel.capolicies'    = 'Conditional Access to brama, która wymusza MFA i blokuje legacy auth. Luki i wykluczenia tutaj to miejsca, którymi atakujący wchodzi wprost.'
        'intel.riskyusers'    = 'Identity Protection oznacza konta, które Microsoft już uznał za ryzykowne. Nieobsłużone ryzyko to alarm pożarowy, którego nikt nie odebrał.'
        # --- ochrona / zaszyfrowane archiwum (Protect.ps1) ---
        'protect.packing'     = 'Zabezpieczam wynik w zaszyfrowanym archiwum (AES-256)...'
        'protect.no7z'        = 'Nie znaleziono 7-Zip (7z/7za/7zz). Pomijam szyfrowanie — pliki zostają jawne. Zainstaluj 7-Zip, aby chronić wynik.'
        'protect.nothing'     = 'Nie ma czego zabezpieczać (brak plików wyjściowych).'
        'protect.done'        = 'Zaszyfrowane archiwum: {0}'
        'protect.removed'     = 'Jawne pliki usunięte — został wyłącznie zaszyfrowane archiwum.'
        'protect.fail'        = 'Szyfrowanie nieudane ({0}). Jawne pliki pozostały nietknięte.'
        'protect.pw_title'    = 'HASŁO ARCHIWUM — POKAZANE RAZ, ZAPISZ JE TERAZ'
        'protect.pw_warn'     = 'To hasło NIE jest nigdzie zapisywane. Zgubisz je — archiwum będzie nie do odzyskania.'
        'protect.ask'         = 'Zaszyfrować wynik w archiwum chronionym hasłem (7-Zip / AES-256)? [t/N]'
        'protect.yes'         = 't'
        'protect.skipped'     = 'Pominięto — pliki zostają jawne.'
        'protect.r1_note'     = 'Uwaga: builder raportu (tryb [2]) potrafi RÓWNIEŻ zaszyfrować wynik. Jeśli zaszyfrujesz dataset TERAZ, builder Pythona NIE odczyta go, dopóki go nie rozpakujesz.'
        'protect.r1_skipped'  = 'Dataset zostaje jawny — zostanie zabezpieczony po zbudowaniu raportu (tryb [2]).'
        'protect.r2_note'     = 'Uwaga: zaszyfrowanego archiwum NIE przetworzy ponownie builder — rozpakuj je, jeśli chcesz przebudować raport.'
        # --- box podsumowania skanu (Common.ps1 / Show-AgScanSummary) ---
        'sum.title'           = 'SKAN ZAKOŃCZONY -- OTO CO UDAŁO SIĘ ZŁAPAĆ'
        'sum.warnings'        = 'Ostrzeżenia'
        'sum.quote'           = '   "Nie sprzedam Twoich danych. Ufasz mi?"  '
        'sum.row.users'       = 'Konta (users)'
        'sum.row.groups'      = 'Grupy'
        'sum.row.roles'       = 'Przypisania ról'
        'sum.row.apps'        = 'Aplikacje / SP'
        'sum.row.applications'= 'Rejestracje app'
        'sum.row.grants'      = 'Zgody OAuth'
        'sum.row.mfa'         = 'Rejestracje MFA'
        'sum.row.audit'       = 'Wpisy audytu (PIM)'
        'sum.row.signins'     = 'Logowania (30 dni)'
        'sum.row.skus'        = 'Licencje (SKU)'
        'sum.row.capolicies'  = 'Polityki CA'
        'sum.row.riskyusers'  = 'Konta atRisk (IdP)'
    }
}

function T {
    <# Zwraca napis dla bieżącego języka ($script:AgLang); fallback: en -> klucz. #>
    param([Parameter(Mandatory)][string]$Key)
    $table = $script:AgStrings[$script:AgLang]
    if ($table -and $table.ContainsKey($Key)) { return $table[$Key] }
    $en = $script:AgStrings['en']
    if ($en.ContainsKey($Key)) { return $en[$Key] }
    return $Key
}
